In [12]:
import pandas as pd
import geopandas as gpd
import shapely
from shapely.geometry import Point

In [24]:
zipcodes= pd.read_csv(r'C:\Users\agmon\Documents\408-HW2\2025_Gaz_zcta_national.txt',sep= '|', dtype={'GEOID' : str})

In [25]:
df=zipcodes

In [26]:
zipcodes

,GEOID,GEOIDFQ,ALAND,AWATER,ALAND_SQMI,AWATER_SQMI,INTPTLAT,INTPTLONG
0,00601,860Z200US00601,166836450,798613,64.416,0.308,18.180555,-66.749961
1,00602,860Z200US00602,78546196,4428428,30.327,1.710,18.361945,-67.175597
2,00603,860Z200US00603,88980553,6253316,34.356,2.414,18.457399,-67.124867
3,00606,860Z200US00606,114825645,12228,44.334,0.005,18.158320,-66.932928
4,00610,860Z200US00610,96150185,4289688,37.124,1.656,18.295304,-67.125180
...,...,...,...,...,...,...,...,...
33786,99923,860Z200US99923,45109238,2117,17.417,0.001,56.000439,-130.037307
33787,99925,860Z200US99925,138891881,22851491,53.626,8.823,55.550203,-132.945947
33788,99926,860Z200US99926,343617420,243547564,132.671,94.034,55.138468,-131.470377
33789,99927,860Z200US99927,12119448,6769693,4.679,2.614,56.331881,-133.606420
33790,99929,860Z200US99929,6251359194,857856580,2413.663,331.220,56.221499,-131.923588

In [28]:
geometry = [Point(xy) for xy in zip(df["INTPTLONG"] , df['INTPTLAT'])]

In [34]:
gdf= gpd.GeoDataFrame(df, geometry=geometry,columns=['GEOID','INTPTLAT', 'INTPTLONG'], crs ="EPSG:4326")

In [35]:
gdf

       GEOID   INTPTLAT   INTPTLONG                     geometry
0      00601  18.180555  -66.749961   POINT (-66.74996 18.18056)
1      00602  18.361945  -67.175597    POINT (-67.1756 18.36194)
2      00603  18.457399  -67.124867    POINT (-67.12487 18.4574)
3      00606  18.158320  -66.932928   POINT (-66.93293 18.15832)
4      00610  18.295304  -67.125180    POINT (-67.12518 18.2953)
...      ...        ...         ...                          ...
33786  99923  56.000439 -130.037307  POINT (-130.03731 56.00044)
33787  99925  55.550203 -132.945947   POINT (-132.94595 55.5502)
33788  99926  55.138468 -131.470377  POINT (-131.47038 55.13847)
33789  99927  56.331881 -133.606420  POINT (-133.60642 56.33188)
33790  99929  56.221499 -131.923588   POINT (-131.92359 56.2215)

[33791 rows x 4 columns]

In [37]:
gdf.to_file("zipcodes_with_points.shp")